module.exports.USERNAME_REGEX = '[a-zA-Z][a-zA-Z0-9-_]{5,16}';
module.exports.EX_USERS_CACHE = 60 * 60; // seconds
module.exports.RECORD_DESC_MIN_LEN = 5;
module.exports.RECORD_DESC_MAX_LEN = 50;
module.exports.RECORD_MIN_PAID = 5;
module.exports.RECORD_MIN_PEOPLE = 1;
module.exports.USER_MIN_USERNAME = 5;
module.exports.USER_MAX_USERNAME = 20;
module.exports.USER_MIN_NAME = 4;
module.exports.USER_MAX_NAME = 25;
module.exports.MAX_AVATAR_SIZE = 5 * 1024 * 1024; // 5 MB